[package]
name = "maelstrom"
version = "0.1.0"
authors = ["LOU Xun <aquarhead@ela.build>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
g-counter = []

[[bin]]
name = "g-counter"
required-features = ["g-counter"]
